/////////////////////////////////////////////////////////////////////////////
// Name:        radlgabout.h
// Purpose:     
// Author:      Vipin Cherian
// Modified by: 
// Created:     16/10/2006 00:23:35
// RCS-ID:      
// Copyright:   
// Licence:     
/////////////////////////////////////////////////////////////////////////////

// Generated by DialogBlocks (unregistered), 16/10/2006 00:23:35

#ifndef _RADLGABOUT_H_
#define _RADLGABOUT_H_

#if defined(__GNUG__) && !defined(NO_GCC_PRAGMA)
#pragma interface "radlgabout.h"
#endif

/*!
 * Includes
 */

////@begin includes
#include "wx/xrc/xmlres.h"
#include "wx/notebook.h"
////@end includes

/*!
 * Forward declarations
 */

////@begin forward declarations
////@end forward declarations

/*!
 * Control identifiers
 */

////@begin control identifiers
#define ID_RADLGABOUT 10000
#define SYMBOL_RADLGABOUT_STYLE wxCAPTION|wxRESIZE_BORDER|wxSYSTEM_MENU|wxCLOSE_BOX
#define SYMBOL_RADLGABOUT_TITLE _("About")
#define SYMBOL_RADLGABOUT_IDNAME ID_RADLGABOUT
#define SYMBOL_RADLGABOUT_SIZE wxSize(400, 300)
#define SYMBOL_RADLGABOUT_POSITION wxDefaultPosition
////@end control identifiers

/*!
 * Compatibility
 */

#ifndef wxCLOSE_BOX
#define wxCLOSE_BOX 0x1000
#endif

/*!
 * raDlgAbout class declaration
 */

class raDlgAbout: public wxDialog
{    
    DECLARE_DYNAMIC_CLASS( raDlgAbout )
    DECLARE_EVENT_TABLE()

public:
    /// Constructors
    raDlgAbout( );
    raDlgAbout( wxWindow* parent, wxWindowID id = SYMBOL_RADLGABOUT_IDNAME, const wxString& caption = SYMBOL_RADLGABOUT_TITLE, const wxPoint& pos = SYMBOL_RADLGABOUT_POSITION, const wxSize& size = SYMBOL_RADLGABOUT_SIZE, long style = SYMBOL_RADLGABOUT_STYLE );

    /// Creation
    bool Create( wxWindow* parent, wxWindowID id = SYMBOL_RADLGABOUT_IDNAME, const wxString& caption = SYMBOL_RADLGABOUT_TITLE, const wxPoint& pos = SYMBOL_RADLGABOUT_POSITION, const wxSize& size = SYMBOL_RADLGABOUT_SIZE, long style = SYMBOL_RADLGABOUT_STYLE );

    /// Initialises member variables
    void Init();

    /// Creates the controls and sizers
    void CreateControls();

////@begin raDlgAbout event handler declarations

    /// wxEVT_COMMAND_BUTTON_CLICKED event handler for ID_ABOUT_BTN_WEB
    void OnAboutBtnWebClick( wxCommandEvent& event );

    /// wxEVT_COMMAND_BUTTON_CLICKED event handler for ID_ABOUT_BTN_OK
    void OnAboutBtnOkClick( wxCommandEvent& event );

////@end raDlgAbout event handler declarations

////@begin raDlgAbout member function declarations

    /// Retrieves bitmap resources
    wxBitmap GetBitmapResource( const wxString& name );

    /// Retrieves icon resources
    wxIcon GetIconResource( const wxString& name );
////@end raDlgAbout member function declarations

    /// Should we show tooltips?
    static bool ShowToolTips();

////@begin raDlgAbout member variables
////@end raDlgAbout member variables
};

#endif
    // _RADLGABOUT_H_
