// rosanne : Twenty-Eight(28) Card Game
// Copyright (C) 2006-2007 Vipin Cherian
//
// This program is free software; you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation; either version 2 of the License, or
// (at your option) any later version.
// 
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
// 
// You should have received a copy of the GNU General Public License
// along with this program; if not, write to the Free Software
// Foundation, Inc., 51 Franklin Street, Fifth Floor, 
// Boston, MA  02110-1301, USA
// Generated by DialogBlocks (unregistered), 11/11/2006-2007 16:57:03

#ifndef _RADLGPREFS_H_
#define _RADLGPREFS_H_

#if defined(__GNUG__) && !defined(NO_GCC_PRAGMA)
#pragma interface "radlgprefs.h"
#endif

/*!
 * Includes
 */

////@begin includes
#include "wx/xrc/xmlres.h"
////@end includes

/*!
 * Forward declarations
 */

////@begin forward declarations
////@end forward declarations

/*!
 * Control identifiers
 */

////@begin control identifiers
#define ID_RADLGPREFS 10006
#define SYMBOL_RADLGPREFS_STYLE wxCAPTION|wxRESIZE_BORDER|wxSYSTEM_MENU|wxCLOSE_BOX
#define SYMBOL_RADLGPREFS_TITLE _("Preferences")
#define SYMBOL_RADLGPREFS_IDNAME ID_RADLGPREFS
#define SYMBOL_RADLGPREFS_SIZE wxSize(400, 300)
#define SYMBOL_RADLGPREFS_POSITION wxDefaultPosition
////@end control identifiers

#define raPREFS_PLAYCARDON_SCLICK 0
#define raPREFS_PLAYCARDON_DCLICK 1
#define raPREFS_CARDBACK_BLUE 0
#define raPREFS_CARDBACK_RED 1
/*!
 * Compatibility
 */

#ifndef wxCLOSE_BOX
#define wxCLOSE_BOX 0x1000
#endif

/*!
 * raDlgPrefs class declaration
 */

class raDlgPrefs: public wxDialog
{    
    DECLARE_DYNAMIC_CLASS( raDlgPrefs )
    DECLARE_EVENT_TABLE()

public:
    /// Constructors
    raDlgPrefs( );
    raDlgPrefs( wxWindow* parent, wxWindowID id = SYMBOL_RADLGPREFS_IDNAME, const wxString& caption = SYMBOL_RADLGPREFS_TITLE, const wxPoint& pos = SYMBOL_RADLGPREFS_POSITION, const wxSize& size = SYMBOL_RADLGPREFS_SIZE, long style = SYMBOL_RADLGPREFS_STYLE );

    /// Creation
    bool Create( wxWindow* parent, wxWindowID id = SYMBOL_RADLGPREFS_IDNAME, const wxString& caption = SYMBOL_RADLGPREFS_TITLE, const wxPoint& pos = SYMBOL_RADLGPREFS_POSITION, const wxSize& size = SYMBOL_RADLGPREFS_SIZE, long style = SYMBOL_RADLGPREFS_STYLE );

    /// Initialises member variables
    void Init();

    /// Creates the controls and sizers
    void CreateControls();

////@begin raDlgPrefs event handler declarations

    /// wxEVT_INIT_DIALOG event handler for ID_RADLGPREFS
    void OnInitDialog( wxInitDialogEvent& event );

    /// wxEVT_COMMAND_BUTTON_CLICKED event handler for ID_PREFS_BTN_APPLY
    void OnPrefsBtnApplyClick( wxCommandEvent& event );

////@end raDlgPrefs event handler declarations

////@begin raDlgPrefs member function declarations

    /// Retrieves bitmap resources
    wxBitmap GetBitmapResource( const wxString& name );

    /// Retrieves icon resources
    wxIcon GetIconResource( const wxString& name );
////@end raDlgPrefs member function declarations

    /// Should we show tooltips?
    static bool ShowToolTips();

////@begin raDlgPrefs member variables
////@end raDlgPrefs member variables
};

#endif
    // _RADLGPREFS_H_
