// rosanne : Twenty-Eight(28) Card Game
// Copyright (C) 2006 Vipin Cherian
//
// This program is free software; you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation; either version 2 of the License, or
// (at your option) any later version.
// 
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
// 
// You should have received a copy of the GNU General Public License
// along with this program; if not, write to the Free Software
// Foundation, Inc., 51 Franklin Street, Fifth Floor, 
// Boston, MA  02110-1301, USA
// Generated by DialogBlocks (unregistered), 11/11/2006 16:57:03

#if defined(__GNUG__) && !defined(NO_GCC_PRAGMA)
#pragma implementation "radlgprefs.h"
#endif

// For compilers that support precompilation, includes "wx/wx.h".
#include "wx/wxprec.h"

#ifdef __BORLANDC__
#pragma hdrstop
#endif

#ifndef WX_PRECOMP
#include "wx/wx.h"
#endif

////@begin includes
////@end includes

#include "ra/radlgprefs.h"
#include "ra/raconfig.h"

////@begin XPM images
////@end XPM images

/*!
 * raDlgPrefs type definition
 */

IMPLEMENT_DYNAMIC_CLASS( raDlgPrefs, wxDialog )

/*!
 * raDlgPrefs event table definition
 */

BEGIN_EVENT_TABLE( raDlgPrefs, wxDialog )

////@begin raDlgPrefs event table entries
    EVT_INIT_DIALOG( raDlgPrefs::OnInitDialog )

    EVT_BUTTON( XRCID("ID_PREFS_BTN_APPLY"), raDlgPrefs::OnPrefsBtnApplyClick )

////@end raDlgPrefs event table entries

END_EVENT_TABLE()

/*!
 * raDlgPrefs constructors
 */

raDlgPrefs::raDlgPrefs( )
{
    Init();
}

raDlgPrefs::raDlgPrefs( wxWindow* parent, wxWindowID id, const wxString& caption, const wxPoint& pos, const wxSize& size, long style )
{
    Init();
    Create(parent, id, caption, pos, size, style);
}

/*!
 * raDlgPrefs creator
 */

bool raDlgPrefs::Create( wxWindow* parent, wxWindowID id, const wxString& caption, const wxPoint& pos, const wxSize& size, long style )
{
////@begin raDlgPrefs creation
    SetExtraStyle(GetExtraStyle()|wxWS_EX_BLOCK_EVENTS);
    SetParent(parent);
    CreateControls();
    if (GetSizer())
    {
        GetSizer()->SetSizeHints(this);
    }
    Centre();
////@end raDlgPrefs creation
    return true;
}

/*!
 * Member initialisation 
 */

void raDlgPrefs::Init()
{
////@begin raDlgPrefs member initialisation
////@end raDlgPrefs member initialisation
}
/*!
 * Control creation for raDlgPrefs
 */

void raDlgPrefs::CreateControls()
{    
////@begin raDlgPrefs content construction
    if (!wxXmlResource::Get()->LoadDialog(this, GetParent(), _T("ID_RADLGPREFS")))
        wxLogError(wxT("Missing wxXmlResource::Get()->Load() in OnInit()?"));
////@end raDlgPrefs content construction

    // Create custom windows not generated automatically here.
////@begin raDlgPrefs content initialisation
////@end raDlgPrefs content initialisation
}

/*!
 * Should we show tooltips?
 */

bool raDlgPrefs::ShowToolTips()
{
    return true;
}

/*!
 * Get bitmap resources
 */

wxBitmap raDlgPrefs::GetBitmapResource( const wxString& name )
{
    // Bitmap retrieval
////@begin raDlgPrefs bitmap retrieval
    wxUnusedVar(name);
    return wxNullBitmap;
////@end raDlgPrefs bitmap retrieval
}

/*!
 * Get icon resources
 */

wxIcon raDlgPrefs::GetIconResource( const wxString& name )
{
    // Icon retrieval
////@begin raDlgPrefs icon retrieval
    wxUnusedVar(name);
    return wxNullIcon;
////@end raDlgPrefs icon retrieval
}
/*!
 * wxEVT_INIT_DIALOG event handler for ID_RADLGPREFS
 */

void raDlgPrefs::OnInitDialog( wxInitDialogEvent& event )
{
	wxComboBox *combo_playcardon;
	wxComboBox *combo_cardback;
	wxCheckBox *check_autoplay;
	raConfData conf_data;

	raConfig::GetInstance()->GetData(&conf_data);
	combo_playcardon = XRCCTRL(*this, "ID_PREFS_CMB_PLAYCARDON", wxComboBox);
	switch(conf_data.prefs_data.play_card_on)
	{
	case raCONFIG_PREFS_PLAYCARDON_SCLICK:
		combo_playcardon->SetSelection(raPREFS_PLAYCARDON_SCLICK);
		break;
	case raCONFIG_PREFS_PLAYCARDON_DCLICK:
		combo_playcardon->SetSelection(raPREFS_PLAYCARDON_DCLICK);
		break;
	default:
		wxLogError(wxString::Format(wxT("Unexpected value. %s:%d"), __FILE__, __LINE__));
		break;
	}

	combo_cardback = XRCCTRL(*this, "ID_PREFS_CMB_CARDBACK", wxComboBox);

	switch(conf_data.prefs_data.card_back)
	{
	case raCONFIG_PREFS_CARDBACK_BLUE:
		combo_cardback->SetSelection(raPREFS_CARDBACK_BLUE);
		break;
	case raCONFIG_PREFS_CARDBACK_RED:
		combo_cardback->SetSelection(raPREFS_CARDBACK_RED);
		break;
	default:
		wxLogError(wxString::Format(wxT("Unexpected value. %s:%d"), __FILE__, __LINE__));
		break;
	}

	check_autoplay = XRCCTRL(*this, "ID_PREFS_CHK_PLAYSINGLEAUTO", wxCheckBox);
	check_autoplay->SetValue(conf_data.prefs_data.auto_play_single);

////@begin wxEVT_INIT_DIALOG event handler for ID_RADLGPREFS in raDlgPrefs.
    // Before editing this code, remove the block markers.
    event.Skip();
////@end wxEVT_INIT_DIALOG event handler for ID_RADLGPREFS in raDlgPrefs. 
}


/*!
 * wxEVT_COMMAND_BUTTON_CLICKED event handler for ID_PREFS_BTN_APPLY
 */

void raDlgPrefs::OnPrefsBtnApplyClick( wxCommandEvent& event )
{
	wxComboBox *combo_playcardon;
	wxComboBox *combo_cardback;
	wxCheckBox *check_autoplay;
	raConfData new_conf;
	raConfig::GetInstance()->GetData(&new_conf);
	combo_playcardon = XRCCTRL(*this, "ID_PREFS_CMB_PLAYCARDON", wxComboBox);
	switch(combo_playcardon->GetSelection())
	{
	case raPREFS_PLAYCARDON_SCLICK:
		new_conf.prefs_data.play_card_on = raCONFIG_PREFS_PLAYCARDON_SCLICK;
		break;
	case raPREFS_PLAYCARDON_DCLICK:
		new_conf.prefs_data.play_card_on = raCONFIG_PREFS_PLAYCARDON_DCLICK;
		break;
	default:
		wxLogError(wxString::Format(wxT("Unexpected value. %s:%d"), __FILE__, __LINE__));
		break;
	}

	combo_cardback = XRCCTRL(*this, "ID_PREFS_CMB_CARDBACK", wxComboBox);

	switch(combo_cardback->GetSelection())
	{
	case raPREFS_CARDBACK_BLUE:
		new_conf.prefs_data.card_back = raCONFIG_PREFS_CARDBACK_BLUE;
		break;
	case raPREFS_CARDBACK_RED:
		new_conf.prefs_data.card_back = raCONFIG_PREFS_CARDBACK_RED;
		break;
	default:
		wxLogError(wxString::Format(wxT("Unexpected value. %s:%d"), __FILE__, __LINE__));
		break;
	}

	check_autoplay = XRCCTRL(*this, "ID_PREFS_CHK_PLAYSINGLEAUTO", wxCheckBox);
	new_conf.prefs_data.auto_play_single = check_autoplay->GetValue();

	raConfig::GetInstance()->SetData(&new_conf);
////@begin wxEVT_COMMAND_BUTTON_CLICKED event handler for ID_PREFS_BTN_APPLY in raDlgPrefs.
    // Before editing this code, remove the block markers.
    event.Skip();
////@end wxEVT_COMMAND_BUTTON_CLICKED event handler for ID_PREFS_BTN_APPLY in raDlgPrefs. 
}


