/////////////////////////////////////////////////////////////////////////////
// Name:        radlgabout.cpp
// Purpose:
// Author:      Vipin Cherian
// Modified by:
// Created:     16/10/2006-2007 00:23:35
// RCS-ID:
// Copyright:
// Licence:
/////////////////////////////////////////////////////////////////////////////

// Generated by DialogBlocks (unregistered), 16/10/2006-2007 00:23:35

#if defined(__GNUG__) && !defined(NO_GCC_PRAGMA)
#pragma implementation "radlgabout.h"
#endif

// For compilers that support precompilation, includes "wx/wx.h".
#include "wx/wxprec.h"

#ifdef __BORLANDC__
#pragma hdrstop
#endif

#ifndef WX_PRECOMP
#include "wx/wx.h"
#endif

////@begin includes
////@end includes

#include "ra/radlgabout.h"
#include "ra/racommon.h"

////@begin XPM images
////@end XPM images

/*!
 * raDlgAbout type definition
 */

IMPLEMENT_DYNAMIC_CLASS( raDlgAbout, wxDialog )

/*!
 * raDlgAbout event table definition
 */

BEGIN_EVENT_TABLE( raDlgAbout, wxDialog )

////@begin raDlgAbout event table entries
    EVT_BUTTON( XRCID("ID_ABOUT_BTN_WEB"), raDlgAbout::OnAboutBtnWebClick )

    EVT_BUTTON( XRCID("ID_ABOUT_BTN_OK"), raDlgAbout::OnAboutBtnOkClick )

////@end raDlgAbout event table entries

END_EVENT_TABLE()

/*!
 * raDlgAbout constructors
 */

raDlgAbout::raDlgAbout( )
{
    Init();
}

raDlgAbout::raDlgAbout( wxWindow* parent, wxWindowID id, const wxString& caption, const wxPoint& pos, const wxSize& size, long style )
{
    Init();
    Create(parent, id, caption, pos, size, style);
}

/*!
 * raDlgAbout creator
 */

bool raDlgAbout::Create( wxWindow* parent, wxWindowID id, const wxString& caption, const wxPoint& pos, const wxSize& size, long style )
{
////@begin raDlgAbout creation
    SetExtraStyle(GetExtraStyle()|wxWS_EX_BLOCK_EVENTS);
    SetParent(parent);
    CreateControls();
    if (GetSizer())
    {
        GetSizer()->SetSizeHints(this);
    }
    Centre();
////@end raDlgAbout creation
    return true;
}

/*!
 * Member initialisation
 */

void raDlgAbout::Init()
{
////@begin raDlgAbout member initialisation
////@end raDlgAbout member initialisation
}
/*!
 * Control creation for raDlgAbout
 */

void raDlgAbout::CreateControls()
{
////@begin raDlgAbout content construction
    if (!wxXmlResource::Get()->LoadDialog(this, GetParent(), _T("ID_RADLGABOUT")))
        wxLogError(wxT("Missing wxXmlResource::Get()->Load() in OnInit()?"));
////@end raDlgAbout content construction

    // Create custom windows not generated automatically here.
////@begin raDlgAbout content initialisation
////@end raDlgAbout content initialisation
}

/*!
 * Should we show tooltips?
 */

bool raDlgAbout::ShowToolTips()
{
    return true;
}

/*!
 * Get bitmap resources
 */

wxBitmap raDlgAbout::GetBitmapResource( const wxString& name )
{
    // Bitmap retrieval
////@begin raDlgAbout bitmap retrieval
    wxUnusedVar(name);
    return wxNullBitmap;
////@end raDlgAbout bitmap retrieval
}

/*!
 * Get icon resources
 */

wxIcon raDlgAbout::GetIconResource( const wxString& name )
{
    // Icon retrieval
////@begin raDlgAbout icon retrieval
    wxUnusedVar(name);
    return wxNullIcon;
////@end raDlgAbout icon retrieval
}
/*!
 * wxEVT_COMMAND_BUTTON_CLICKED event handler for ID_ABOUT_BTN_OK
 */

void raDlgAbout::OnAboutBtnOkClick( wxCommandEvent& event )
{
////@begin wxEVT_COMMAND_BUTTON_CLICKED event handler for ID_ABOUT_BTN_OK in raDlgAbout.
    // Before editing this code, remove the block markers.
    Destroy();
////@end wxEVT_COMMAND_BUTTON_CLICKED event handler for ID_ABOUT_BTN_OK in raDlgAbout.
}


/*!
 * wxEVT_COMMAND_BUTTON_CLICKED event handler for ID_ABOUT_BTN_WEB
 */

void raDlgAbout::OnAboutBtnWebClick( wxCommandEvent& event )
{
	wxLaunchDefaultBrowser(ra_APP_URL);
    event.Skip();

}


